// flow-typed signature: eee876dedc62d72c94dd48a7c6194834
// flow-typed version: <<STUB>>/http-status_v^1.0.1/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'http-status'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'http-status' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'http-status/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'http-status/lib/index.js' {
  declare module.exports: $Exports<'http-status/lib/index'>;
}
